/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author 1
 */
public class ThuThuChiTietPhieuXuat extends javax.swing.JFrame {

    /**
     * Creates new form ThuThuChiTietPhieuXuat
     */
    public ThuThuChiTietPhieuXuat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PhieuXuatTab = new javax.swing.JPanel();
        tenSachLabel = new javax.swing.JLabel();
        K_tieuDe = new javax.swing.JLabel();
        maSachLabel = new javax.swing.JLabel();
        ghiChuLabel = new javax.swing.JLabel();
        maSachField = new javax.swing.JTextField();
        tenSachField = new javax.swing.JTextField();
        soLuongLabel = new javax.swing.JLabel();
        soLuongField1 = new javax.swing.JTextField();
        ghiChuField = new javax.swing.JTextField();
        giaField = new javax.swing.JTextField();
        tongTienField = new javax.swing.JTextField();
        tongTienLabel = new javax.swing.JLabel();
        giaLabel = new javax.swing.JLabel();
        maThanhLyLabel = new javax.swing.JLabel();
        maThanhLyField = new javax.swing.JTextField();
        ngayThanhlyLabel = new javax.swing.JLabel();
        ngayThanhlyField = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnK_veTrangTruoc = new javax.swing.JButton();
        btnK_luuChiTiet = new javax.swing.JButton();
        btnK_suaChiTiet = new javax.swing.JButton();
        btnK_lamMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PhieuXuatTab.setBackground(new java.awt.Color(205, 205, 255));
        PhieuXuatTab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        tenSachLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        tenSachLabel.setForeground(new java.awt.Color(0, 0, 0));
        tenSachLabel.setText("Tên sách:");

        K_tieuDe.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        K_tieuDe.setForeground(new java.awt.Color(0, 0, 0));
        K_tieuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill.png"))); // NOI18N
        K_tieuDe.setText("Chi Tiết Phiếu Xuất");

        maSachLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        maSachLabel.setForeground(new java.awt.Color(0, 0, 0));
        maSachLabel.setText("Mã sách:");

        ghiChuLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ghiChuLabel.setForeground(new java.awt.Color(0, 0, 0));
        ghiChuLabel.setText("Ghi chú:");

        maSachField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maSachFieldActionPerformed(evt);
            }
        });
        maSachField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                maSachFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maSachFieldKeyTyped(evt);
            }
        });

        tenSachField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenSachFieldActionPerformed(evt);
            }
        });
        tenSachField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tenSachFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tenSachFieldKeyTyped(evt);
            }
        });

        soLuongLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        soLuongLabel.setForeground(new java.awt.Color(0, 0, 0));
        soLuongLabel.setText("Số lượng:");

        soLuongField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soLuongField1ActionPerformed(evt);
            }
        });
        soLuongField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                soLuongField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soLuongField1KeyTyped(evt);
            }
        });

        ghiChuField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ghiChuFieldActionPerformed(evt);
            }
        });
        ghiChuField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ghiChuFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ghiChuFieldKeyTyped(evt);
            }
        });

        giaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giaFieldActionPerformed(evt);
            }
        });
        giaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                giaFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                giaFieldKeyTyped(evt);
            }
        });

        tongTienField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tongTienFieldActionPerformed(evt);
            }
        });
        tongTienField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tongTienFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tongTienFieldKeyTyped(evt);
            }
        });

        tongTienLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        tongTienLabel.setForeground(new java.awt.Color(0, 0, 0));
        tongTienLabel.setText("Tổng tiền:");

        giaLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        giaLabel.setForeground(new java.awt.Color(0, 0, 0));
        giaLabel.setText("Giá:");

        maThanhLyLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        maThanhLyLabel.setForeground(new java.awt.Color(0, 0, 0));
        maThanhLyLabel.setText("Mã thanh lý:");

        maThanhLyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maThanhLyFieldActionPerformed(evt);
            }
        });
        maThanhLyField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                maThanhLyFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maThanhLyFieldKeyTyped(evt);
            }
        });

        ngayThanhlyLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ngayThanhlyLabel.setForeground(new java.awt.Color(0, 0, 0));
        ngayThanhlyLabel.setText("Ngày thanh lý:");

        ngayThanhlyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngayThanhlyFieldActionPerformed(evt);
            }
        });
        ngayThanhlyField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ngayThanhlyFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ngayThanhlyFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PhieuXuatTabLayout = new javax.swing.GroupLayout(PhieuXuatTab);
        PhieuXuatTab.setLayout(PhieuXuatTabLayout);
        PhieuXuatTabLayout.setHorizontalGroup(
            PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhieuXuatTabLayout.createSequentialGroup()
                .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PhieuXuatTabLayout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(K_tieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PhieuXuatTabLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(soLuongField1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PhieuXuatTabLayout.createSequentialGroup()
                                        .addComponent(maThanhLyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(maThanhLyField, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PhieuXuatTabLayout.createSequentialGroup()
                                        .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(maSachLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tenSachLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(maSachField, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                            .addComponent(tenSachField)))))
                            .addComponent(soLuongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95)
                        .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PhieuXuatTabLayout.createSequentialGroup()
                                .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(giaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tongTienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ghiChuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ghiChuField)
                                    .addComponent(giaField)
                                    .addComponent(tongTienField, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)))
                            .addGroup(PhieuXuatTabLayout.createSequentialGroup()
                                .addComponent(ngayThanhlyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ngayThanhlyField)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        PhieuXuatTabLayout.setVerticalGroup(
            PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhieuXuatTabLayout.createSequentialGroup()
                .addComponent(K_tieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maThanhLyLabel)
                    .addComponent(maThanhLyField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngayThanhlyLabel)
                    .addComponent(ngayThanhlyField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PhieuXuatTabLayout.createSequentialGroup()
                        .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maSachLabel)
                            .addComponent(maSachField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tenSachLabel)
                            .addComponent(tenSachField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PhieuXuatTabLayout.createSequentialGroup()
                        .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(giaLabel)
                            .addComponent(giaField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tongTienLabel)
                            .addComponent(tongTienField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(soLuongLabel)
                        .addComponent(soLuongField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PhieuXuatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ghiChuLabel)
                        .addComponent(ghiChuField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 205));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Số Lượng", "Ghi Chú", "Giá", "Tổng Tiền", "Ngày thanh lý", "Ghi chú"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        btnK_veTrangTruoc.setBackground(new java.awt.Color(255, 204, 204));
        btnK_veTrangTruoc.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_veTrangTruoc.setForeground(new java.awt.Color(0, 0, 0));
        btnK_veTrangTruoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_previous.png"))); // NOI18N
        btnK_veTrangTruoc.setText("Về trang trước");
        btnK_veTrangTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_veTrangTruocActionPerformed(evt);
            }
        });

        btnK_luuChiTiet.setBackground(new java.awt.Color(255, 204, 204));
        btnK_luuChiTiet.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_luuChiTiet.setForeground(new java.awt.Color(0, 0, 0));
        btnK_luuChiTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/luu.png"))); // NOI18N
        btnK_luuChiTiet.setText("Cập nhật");
        btnK_luuChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_luuChiTietActionPerformed(evt);
            }
        });

        btnK_suaChiTiet.setBackground(new java.awt.Color(255, 204, 204));
        btnK_suaChiTiet.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_suaChiTiet.setForeground(new java.awt.Color(0, 0, 0));
        btnK_suaChiTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exchange1.png"))); // NOI18N
        btnK_suaChiTiet.setText("Sửa thông tin");
        btnK_suaChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_suaChiTietActionPerformed(evt);
            }
        });

        btnK_lamMoi.setBackground(new java.awt.Color(255, 204, 204));
        btnK_lamMoi.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_lamMoi.setForeground(new java.awt.Color(0, 0, 0));
        btnK_lamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eraser.png"))); // NOI18N
        btnK_lamMoi.setText("Làm mới");
        btnK_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_lamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnK_luuChiTiet)
                .addGap(18, 18, 18)
                .addComponent(btnK_suaChiTiet)
                .addGap(18, 18, 18)
                .addComponent(btnK_lamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnK_veTrangTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnK_luuChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnK_suaChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnK_lamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnK_veTrangTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PhieuXuatTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PhieuXuatTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maSachFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maSachFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maSachFieldActionPerformed

    private void maSachFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maSachFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_maSachFieldKeyReleased

    private void maSachFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maSachFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_maSachFieldKeyTyped

    private void tenSachFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenSachFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenSachFieldActionPerformed

    private void tenSachFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tenSachFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tenSachFieldKeyReleased

    private void tenSachFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tenSachFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tenSachFieldKeyTyped

    private void soLuongField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soLuongField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soLuongField1ActionPerformed

    private void soLuongField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soLuongField1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_soLuongField1KeyReleased

    private void soLuongField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soLuongField1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_soLuongField1KeyTyped

    private void ghiChuFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ghiChuFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ghiChuFieldActionPerformed

    private void ghiChuFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ghiChuFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ghiChuFieldKeyReleased

    private void ghiChuFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ghiChuFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ghiChuFieldKeyTyped

    private void giaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giaFieldActionPerformed

    private void giaFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_giaFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_giaFieldKeyReleased

    private void giaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_giaFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_giaFieldKeyTyped

    private void tongTienFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tongTienFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tongTienFieldActionPerformed

    private void tongTienFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tongTienFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tongTienFieldKeyReleased

    private void tongTienFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tongTienFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tongTienFieldKeyTyped

    private void maThanhLyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maThanhLyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maThanhLyFieldActionPerformed

    private void maThanhLyFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maThanhLyFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_maThanhLyFieldKeyReleased

    private void maThanhLyFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maThanhLyFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_maThanhLyFieldKeyTyped

    private void ngayThanhlyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngayThanhlyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngayThanhlyFieldActionPerformed

    private void ngayThanhlyFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ngayThanhlyFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ngayThanhlyFieldKeyReleased

    private void ngayThanhlyFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ngayThanhlyFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ngayThanhlyFieldKeyTyped

    private void btnK_luuChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_luuChiTietActionPerformed

    }//GEN-LAST:event_btnK_luuChiTietActionPerformed

    private void btnK_suaChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_suaChiTietActionPerformed

    }//GEN-LAST:event_btnK_suaChiTietActionPerformed

    private void btnK_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_lamMoiActionPerformed

    }//GEN-LAST:event_btnK_lamMoiActionPerformed

    private void btnK_veTrangTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_veTrangTruocActionPerformed

    }//GEN-LAST:event_btnK_veTrangTruocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThuThuChiTietPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThuThuChiTietPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThuThuChiTietPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThuThuChiTietPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThuThuChiTietPhieuXuat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel K_tieuDe;
    private javax.swing.JPanel PhieuXuatTab;
    private javax.swing.JButton btnK_lamMoi;
    private javax.swing.JButton btnK_luuChiTiet;
    private javax.swing.JButton btnK_suaChiTiet;
    private javax.swing.JButton btnK_veTrangTruoc;
    private javax.swing.JTextField ghiChuField;
    private javax.swing.JLabel ghiChuLabel;
    private javax.swing.JTextField giaField;
    private javax.swing.JLabel giaLabel;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField maSachField;
    private javax.swing.JLabel maSachLabel;
    private javax.swing.JTextField maThanhLyField;
    private javax.swing.JLabel maThanhLyLabel;
    private javax.swing.JTextField ngayThanhlyField;
    private javax.swing.JLabel ngayThanhlyLabel;
    private javax.swing.JTextField soLuongField1;
    private javax.swing.JLabel soLuongLabel;
    private javax.swing.JTextField tenSachField;
    private javax.swing.JLabel tenSachLabel;
    private javax.swing.JTextField tongTienField;
    private javax.swing.JLabel tongTienLabel;
    // End of variables declaration//GEN-END:variables
}
