/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author 1
 */
public class TrangChuThuThu_QLPNhap extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuThuThu_QLPNhap
     */
    public TrangChuThuThu_QLPNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPK_tieuDe = new javax.swing.JPanel();
        lbK_tieuDe = new javax.swing.JLabel();
        btnK_veTrangTruoc = new javax.swing.JButton();
        jPK_qlPM = new javax.swing.JPanel();
        jPK_themPM = new javax.swing.JPanel();
        maPhieunhapLabel = new javax.swing.JLabel();
        maPhieuXuatField = new javax.swing.JTextField();
        ngayNhạpLabel = new javax.swing.JLabel();
        ngayXuatField = new javax.swing.JTextField();
        ngayXuatCungCap = new javax.swing.JLabel();
        ngayXuatField1 = new javax.swing.JTextField();
        jPK_themMaSach = new javax.swing.JPanel();
        tenSachField = new javax.swing.JTextField();
        labelTensach = new javax.swing.JLabel();
        maSachField = new javax.swing.JTextField();
        labelMasach = new javax.swing.JLabel();
        maPhieuNhapLabelIcon = new javax.swing.JLabel();
        comboBoxMaPNhap = new javax.swing.JComboBox<>();
        labelMaTGia = new javax.swing.JLabel();
        maTGiaFiedl = new javax.swing.JTextField();
        labelTenTGia = new javax.swing.JLabel();
        tenTGiaField = new javax.swing.JTextField();
        labelMaTLoai = new javax.swing.JLabel();
        maTLoaiField = new javax.swing.JTextField();
        labelNgayXBan = new javax.swing.JLabel();
        nxbField = new javax.swing.JTextField();
        labelNXuatBan = new javax.swing.JLabel();
        namXBField = new javax.swing.JTextField();
        labelSoLuong = new javax.swing.JLabel();
        soLuongField = new javax.swing.JTextField();
        labelGiaNhap = new javax.swing.JLabel();
        GNhapField = new javax.swing.JTextField();
        labelTongTien = new javax.swing.JLabel();
        tongTienField = new javax.swing.JTextField();
        jPK_button = new javax.swing.JPanel();
        jPK_btnQLPM = new javax.swing.JPanel();
        btnK_themPN = new javax.swing.JButton();
        btnK_luuPN = new javax.swing.JButton();
        btnExportPN = new javax.swing.JButton();
        btnK_suaPN = new javax.swing.JButton();
        btnRefreshPN = new javax.swing.JButton();
        DelBtnNhap = new javax.swing.JButton();
        jPK_btnQLS = new javax.swing.JPanel();
        btnK_themMaSach = new javax.swing.JButton();
        btnK_lamMoiPN = new javax.swing.JButton();
        btnK_luuMaSach = new javax.swing.JButton();
        btnK_suaPN1 = new javax.swing.JButton();
        DelBtn = new javax.swing.JButton();
        DelBtnImport = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPK_tieuDe.setBackground(new java.awt.Color(255, 204, 204));

        lbK_tieuDe.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbK_tieuDe.setForeground(java.awt.Color.darkGray);
        lbK_tieuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill.png"))); // NOI18N
        lbK_tieuDe.setText("QUẢN LÝ PHIẾU NHẬP");

        btnK_veTrangTruoc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnK_veTrangTruoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_previous.png"))); // NOI18N
        btnK_veTrangTruoc.setText("Về trang trước");
        btnK_veTrangTruoc.setToolTipText("");
        btnK_veTrangTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_veTrangTruocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPK_tieuDeLayout = new javax.swing.GroupLayout(jPK_tieuDe);
        jPK_tieuDe.setLayout(jPK_tieuDeLayout);
        jPK_tieuDeLayout.setHorizontalGroup(
            jPK_tieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPK_tieuDeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnK_veTrangTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329)
                .addComponent(lbK_tieuDe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPK_tieuDeLayout.setVerticalGroup(
            jPK_tieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPK_tieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPK_tieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbK_tieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnK_veTrangTruoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPK_qlPM.setBackground(new java.awt.Color(255, 255, 204));

        jPK_themPM.setBackground(new java.awt.Color(204, 204, 255));
        jPK_themPM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        maPhieunhapLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        maPhieunhapLabel.setForeground(new java.awt.Color(0, 0, 0));
        maPhieunhapLabel.setText("Mã phiếu nhập:");

        maPhieuXuatField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        ngayNhạpLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ngayNhạpLabel.setForeground(new java.awt.Color(0, 0, 0));
        ngayNhạpLabel.setText("Ngày nhập:");

        ngayXuatField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        ngayXuatCungCap.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ngayXuatCungCap.setForeground(new java.awt.Color(0, 0, 0));
        ngayXuatCungCap.setText("Ngày cung cấp:");

        ngayXuatField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPK_themPMLayout = new javax.swing.GroupLayout(jPK_themPM);
        jPK_themPM.setLayout(jPK_themPMLayout);
        jPK_themPMLayout.setHorizontalGroup(
            jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPK_themPMLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ngayNhạpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maPhieunhapLabel)
                    .addComponent(ngayXuatCungCap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ngayXuatField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(maPhieuXuatField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ngayXuatField1))
                .addGap(138, 138, 138))
        );
        jPK_themPMLayout.setVerticalGroup(
            jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPK_themPMLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maPhieunhapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maPhieuXuatField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngayNhạpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngayXuatField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngayXuatCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngayXuatField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPK_themMaSach.setBackground(new java.awt.Color(204, 204, 255));
        jPK_themMaSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tenSachField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tenSachField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenSachFieldActionPerformed(evt);
            }
        });

        labelTensach.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelTensach.setForeground(new java.awt.Color(0, 0, 0));
        labelTensach.setText("Tên sách:");

        maSachField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        maSachField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maSachFieldActionPerformed(evt);
            }
        });

        labelMasach.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelMasach.setForeground(new java.awt.Color(0, 0, 0));
        labelMasach.setText("Mã sách:");

        maPhieuNhapLabelIcon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        maPhieuNhapLabelIcon.setForeground(new java.awt.Color(0, 0, 0));
        maPhieuNhapLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/open-book.png"))); // NOI18N
        maPhieuNhapLabelIcon.setText("Mã phiếu nhập:");

        comboBoxMaPNhap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        comboBoxMaPNhap.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxMaPNhapItemStateChanged(evt);
            }
        });
        comboBoxMaPNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMaPNhapActionPerformed(evt);
            }
        });

        labelMaTGia.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelMaTGia.setForeground(new java.awt.Color(0, 0, 0));
        labelMaTGia.setText("Mã tác giả:");

        maTGiaFiedl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        maTGiaFiedl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maTGiaFiedlActionPerformed(evt);
            }
        });

        labelTenTGia.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelTenTGia.setForeground(new java.awt.Color(0, 0, 0));
        labelTenTGia.setText("Tên tác giả:");

        tenTGiaField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tenTGiaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenTGiaFieldActionPerformed(evt);
            }
        });

        labelMaTLoai.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelMaTLoai.setForeground(new java.awt.Color(0, 0, 0));
        labelMaTLoai.setText("Mã thể loại:");

        maTLoaiField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        maTLoaiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maTLoaiFieldActionPerformed(evt);
            }
        });

        labelNgayXBan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelNgayXBan.setForeground(new java.awt.Color(0, 0, 0));
        labelNgayXBan.setText("Nhà xuất bản:");

        nxbField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nxbField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxbFieldActionPerformed(evt);
            }
        });

        labelNXuatBan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelNXuatBan.setForeground(new java.awt.Color(0, 0, 0));
        labelNXuatBan.setText("Năm xuất bản:");

        namXBField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        namXBField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namXBFieldActionPerformed(evt);
            }
        });

        labelSoLuong.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelSoLuong.setForeground(new java.awt.Color(0, 0, 0));
        labelSoLuong.setText("Số lượng:");

        soLuongField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        soLuongField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soLuongFieldActionPerformed(evt);
            }
        });

        labelGiaNhap.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelGiaNhap.setForeground(new java.awt.Color(0, 0, 0));
        labelGiaNhap.setText("Giá nhập:");

        GNhapField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        GNhapField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GNhapFieldActionPerformed(evt);
            }
        });

        labelTongTien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelTongTien.setForeground(new java.awt.Color(0, 0, 0));
        labelTongTien.setText("Tổng tiền:");

        tongTienField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tongTienField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tongTienFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPK_themMaSachLayout = new javax.swing.GroupLayout(jPK_themMaSach);
        jPK_themMaSach.setLayout(jPK_themMaSachLayout);
        jPK_themMaSachLayout.setHorizontalGroup(
            jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                        .addComponent(maPhieuNhapLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxMaPNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPK_themMaSachLayout.createSequentialGroup()
                        .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                                .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelMasach, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPK_themMaSachLayout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(maSachField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(labelTensach))
                            .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                                .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMaTGia)
                                    .addComponent(labelSoLuong))
                                .addGap(18, 18, 18)
                                .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                                        .addComponent(soLuongField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelGiaNhap))
                                    .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                                        .addComponent(maTGiaFiedl, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelTenTGia)))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                                .addComponent(labelMaTLoai)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maTLoaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                                .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(GNhapField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tenSachField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                        .addComponent(tenTGiaField, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTongTien)
                                    .addComponent(labelNXuatBan)
                                    .addComponent(labelNgayXBan))))
                        .addGap(18, 18, 18)
                        .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namXBField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nxbField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tongTienField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(191, 191, 191))))
        );
        jPK_themMaSachLayout.setVerticalGroup(
            jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maPhieuNhapLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMaPNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMaTLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maTLoaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMasach, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maSachField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTensach, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenSachField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNgayXBan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nxbField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMaTGia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maTGiaFiedl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTenTGia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenTGiaField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namXBField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soLuongField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GNhapField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tongTienField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jPK_button.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPK_buttonLayout = new javax.swing.GroupLayout(jPK_button);
        jPK_button.setLayout(jPK_buttonLayout);
        jPK_buttonLayout.setHorizontalGroup(
            jPK_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
        jPK_buttonLayout.setVerticalGroup(
            jPK_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );

        jPK_btnQLPM.setBackground(new java.awt.Color(204, 204, 255));
        jPK_btnQLPM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPK_btnQLPM.setPreferredSize(new java.awt.Dimension(520, 84));

        btnK_themPN.setBackground(new java.awt.Color(255, 204, 204));
        btnK_themPN.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_themPN.setForeground(new java.awt.Color(0, 0, 0));
        btnK_themPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        btnK_themPN.setText("Thêm");
        btnK_themPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_themPNActionPerformed(evt);
            }
        });

        btnK_luuPN.setBackground(new java.awt.Color(255, 204, 204));
        btnK_luuPN.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_luuPN.setForeground(new java.awt.Color(0, 0, 0));
        btnK_luuPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/luu.png"))); // NOI18N
        btnK_luuPN.setText("Lưu");
        btnK_luuPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_luuPNActionPerformed(evt);
            }
        });

        btnExportPN.setBackground(new java.awt.Color(255, 204, 204));
        btnExportPN.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnExportPN.setForeground(new java.awt.Color(0, 0, 0));
        btnExportPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/R_pixian_ai.png"))); // NOI18N
        btnExportPN.setText("Xuất");
        btnExportPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportPNActionPerformed(evt);
            }
        });

        btnK_suaPN.setBackground(new java.awt.Color(255, 204, 204));
        btnK_suaPN.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_suaPN.setForeground(new java.awt.Color(0, 0, 0));
        btnK_suaPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exchange1.png"))); // NOI18N
        btnK_suaPN.setText("Sửa");
        btnK_suaPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_suaPNActionPerformed(evt);
            }
        });

        btnRefreshPN.setBackground(new java.awt.Color(255, 204, 204));
        btnRefreshPN.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnRefreshPN.setForeground(new java.awt.Color(0, 0, 0));
        btnRefreshPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eraser.png"))); // NOI18N
        btnRefreshPN.setText("Làm mới");
        btnRefreshPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshPNActionPerformed(evt);
            }
        });

        DelBtnNhap.setBackground(new java.awt.Color(255, 204, 204));
        DelBtnNhap.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        DelBtnNhap.setForeground(new java.awt.Color(0, 0, 0));
        DelBtnNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa.png"))); // NOI18N
        DelBtnNhap.setText("Xóa");
        DelBtnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelBtnNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPK_btnQLPMLayout = new javax.swing.GroupLayout(jPK_btnQLPM);
        jPK_btnQLPM.setLayout(jPK_btnQLPMLayout);
        jPK_btnQLPMLayout.setHorizontalGroup(
            jPK_btnQLPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPK_btnQLPMLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPK_btnQLPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPK_btnQLPMLayout.createSequentialGroup()
                        .addComponent(btnK_themPN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnK_suaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPK_btnQLPMLayout.createSequentialGroup()
                        .addComponent(btnK_luuPN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExportPN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPK_btnQLPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRefreshPN)
                    .addComponent(DelBtnNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPK_btnQLPMLayout.setVerticalGroup(
            jPK_btnQLPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPK_btnQLPMLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPK_btnQLPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnK_themPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnK_suaPN)
                    .addComponent(DelBtnNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPK_btnQLPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnK_luuPN)
                    .addComponent(btnExportPN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshPN))
                .addGap(21, 21, 21))
        );

        jPK_btnQLS.setBackground(new java.awt.Color(204, 204, 255));
        jPK_btnQLS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPK_btnQLS.setPreferredSize(new java.awt.Dimension(540, 84));

        btnK_themMaSach.setBackground(new java.awt.Color(255, 204, 204));
        btnK_themMaSach.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_themMaSach.setForeground(new java.awt.Color(0, 0, 0));
        btnK_themMaSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/them.png"))); // NOI18N
        btnK_themMaSach.setText("Thêm");
        btnK_themMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_themMaSachActionPerformed(evt);
            }
        });

        btnK_lamMoiPN.setBackground(new java.awt.Color(255, 204, 204));
        btnK_lamMoiPN.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_lamMoiPN.setForeground(new java.awt.Color(0, 0, 0));
        btnK_lamMoiPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eraser.png"))); // NOI18N
        btnK_lamMoiPN.setText("Làm mới");
        btnK_lamMoiPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_lamMoiPNActionPerformed(evt);
            }
        });

        btnK_luuMaSach.setBackground(new java.awt.Color(255, 204, 204));
        btnK_luuMaSach.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_luuMaSach.setForeground(new java.awt.Color(0, 0, 0));
        btnK_luuMaSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/luu.png"))); // NOI18N
        btnK_luuMaSach.setText("Lưu");
        btnK_luuMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_luuMaSachActionPerformed(evt);
            }
        });

        btnK_suaPN1.setBackground(new java.awt.Color(255, 204, 204));
        btnK_suaPN1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_suaPN1.setForeground(new java.awt.Color(0, 0, 0));
        btnK_suaPN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exchange1.png"))); // NOI18N
        btnK_suaPN1.setText("Sửa");
        btnK_suaPN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_suaPN1ActionPerformed(evt);
            }
        });

        DelBtn.setBackground(new java.awt.Color(255, 204, 204));
        DelBtn.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        DelBtn.setForeground(new java.awt.Color(0, 0, 0));
        DelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa.png"))); // NOI18N
        DelBtn.setText("Xóa");
        DelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelBtnActionPerformed(evt);
            }
        });

        DelBtnImport.setBackground(new java.awt.Color(255, 204, 204));
        DelBtnImport.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        DelBtnImport.setForeground(new java.awt.Color(0, 0, 0));
        DelBtnImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/OIP_pixian_ai.png"))); // NOI18N
        DelBtnImport.setText("Import");
        DelBtnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelBtnImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPK_btnQLSLayout = new javax.swing.GroupLayout(jPK_btnQLS);
        jPK_btnQLS.setLayout(jPK_btnQLSLayout);
        jPK_btnQLSLayout.setHorizontalGroup(
            jPK_btnQLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPK_btnQLSLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnK_themMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnK_suaPN1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnK_luuMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnK_lamMoiPN)
                .addGap(18, 18, 18)
                .addComponent(DelBtnImport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPK_btnQLSLayout.setVerticalGroup(
            jPK_btnQLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPK_btnQLSLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPK_btnQLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnK_themMaSach)
                    .addComponent(btnK_suaPN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnK_luuMaSach)
                    .addComponent(btnK_lamMoiPN)
                    .addComponent(DelBtnImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã phiếu xuất", "Ngày nhập", "Ngày cung cấp"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu nhập", "Mã sách", "Tên sách", "Mã tác giả", "Tên tác giẩ", "Mã thể loại", "Nhà xuất bản", "Năm xuất bản", "Giá nhập", "Số lượng", "Tổng tiền"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPK_qlPMLayout = new javax.swing.GroupLayout(jPK_qlPM);
        jPK_qlPM.setLayout(jPK_qlPMLayout);
        jPK_qlPMLayout.setHorizontalGroup(
            jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPK_qlPMLayout.createSequentialGroup()
                .addComponent(jPK_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1293, 1293, 1293))
            .addGroup(jPK_qlPMLayout.createSequentialGroup()
                .addGroup(jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPK_btnQLPM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                    .addGroup(jPK_qlPMLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPK_themPM, javax.swing.GroupLayout.PREFERRED_SIZE, 429, Short.MAX_VALUE))))
                .addGap(24, 24, 24)
                .addGroup(jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPK_btnQLS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1113, Short.MAX_VALUE)
                    .addComponent(jPK_themMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPK_qlPMLayout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())))
        );
        jPK_qlPMLayout.setVerticalGroup(
            jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPK_qlPMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPK_themPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPK_themMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPK_btnQLS, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jPK_btnQLPM, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(430, 430, 430)
                .addComponent(jPK_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPK_tieuDe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPK_qlPM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPK_tieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPK_qlPM, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnK_veTrangTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_veTrangTruocActionPerformed

    }//GEN-LAST:event_btnK_veTrangTruocActionPerformed

    private void tenSachFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenSachFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenSachFieldActionPerformed

    private void maSachFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maSachFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maSachFieldActionPerformed

    private void comboBoxMaPNhapItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxMaPNhapItemStateChanged

    }//GEN-LAST:event_comboBoxMaPNhapItemStateChanged

    private void comboBoxMaPNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMaPNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxMaPNhapActionPerformed

    private void maTGiaFiedlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maTGiaFiedlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maTGiaFiedlActionPerformed

    private void tenTGiaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenTGiaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenTGiaFieldActionPerformed

    private void maTLoaiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maTLoaiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maTLoaiFieldActionPerformed

    private void nxbFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxbFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nxbFieldActionPerformed

    private void namXBFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namXBFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namXBFieldActionPerformed

    private void soLuongFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soLuongFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soLuongFieldActionPerformed

    private void GNhapFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GNhapFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GNhapFieldActionPerformed

    private void tongTienFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tongTienFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tongTienFieldActionPerformed

    private void btnK_themPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_themPNActionPerformed

    }//GEN-LAST:event_btnK_themPNActionPerformed

    private void btnK_luuPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_luuPNActionPerformed

    }//GEN-LAST:event_btnK_luuPNActionPerformed

    private void btnExportPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportPNActionPerformed

    private void btnK_suaPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_suaPNActionPerformed

    }//GEN-LAST:event_btnK_suaPNActionPerformed

    private void btnRefreshPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshPNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshPNActionPerformed

    private void DelBtnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelBtnNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DelBtnNhapActionPerformed

    private void btnK_themMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_themMaSachActionPerformed

    }//GEN-LAST:event_btnK_themMaSachActionPerformed

    private void btnK_lamMoiPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_lamMoiPNActionPerformed

    }//GEN-LAST:event_btnK_lamMoiPNActionPerformed

    private void btnK_luuMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_luuMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnK_luuMaSachActionPerformed

    private void btnK_suaPN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_suaPN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnK_suaPN1ActionPerformed

    private void DelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelBtnActionPerformed

    }//GEN-LAST:event_DelBtnActionPerformed

    private void DelBtnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelBtnImportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DelBtnImportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuThuThu_QLPNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuThuThu_QLPNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuThuThu_QLPNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuThuThu_QLPNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuThuThu_QLPNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DelBtn;
    private javax.swing.JButton DelBtnImport;
    private javax.swing.JButton DelBtnNhap;
    private javax.swing.JTextField GNhapField;
    private javax.swing.JButton btnExportPN;
    private javax.swing.JButton btnK_lamMoiPN;
    private javax.swing.JButton btnK_luuMaSach;
    private javax.swing.JButton btnK_luuPN;
    private javax.swing.JButton btnK_suaPN;
    private javax.swing.JButton btnK_suaPN1;
    private javax.swing.JButton btnK_themMaSach;
    private javax.swing.JButton btnK_themPN;
    private javax.swing.JButton btnK_veTrangTruoc;
    private javax.swing.JButton btnRefreshPN;
    private javax.swing.JComboBox<String> comboBoxMaPNhap;
    private javax.swing.JPanel jPK_btnQLPM;
    private javax.swing.JPanel jPK_btnQLS;
    private javax.swing.JPanel jPK_button;
    private javax.swing.JPanel jPK_qlPM;
    private javax.swing.JPanel jPK_themMaSach;
    private javax.swing.JPanel jPK_themPM;
    private javax.swing.JPanel jPK_tieuDe;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelGiaNhap;
    private javax.swing.JLabel labelMaTGia;
    private javax.swing.JLabel labelMaTLoai;
    private javax.swing.JLabel labelMasach;
    private javax.swing.JLabel labelNXuatBan;
    private javax.swing.JLabel labelNgayXBan;
    private javax.swing.JLabel labelSoLuong;
    private javax.swing.JLabel labelTenTGia;
    private javax.swing.JLabel labelTensach;
    private javax.swing.JLabel labelTongTien;
    private javax.swing.JLabel lbK_tieuDe;
    private javax.swing.JLabel maPhieuNhapLabelIcon;
    private javax.swing.JTextField maPhieuXuatField;
    private javax.swing.JLabel maPhieunhapLabel;
    private javax.swing.JTextField maSachField;
    private javax.swing.JTextField maTGiaFiedl;
    private javax.swing.JTextField maTLoaiField;
    private javax.swing.JTextField namXBField;
    private javax.swing.JLabel ngayNhạpLabel;
    private javax.swing.JLabel ngayXuatCungCap;
    private javax.swing.JTextField ngayXuatField;
    private javax.swing.JTextField ngayXuatField1;
    private javax.swing.JTextField nxbField;
    private javax.swing.JTextField soLuongField;
    private javax.swing.JTextField tenSachField;
    private javax.swing.JTextField tenTGiaField;
    private javax.swing.JTextField tongTienField;
    // End of variables declaration//GEN-END:variables
}
