/*

 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author 1
 */
public class TrangChuThuThu_QLPXuat extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuThuThu_QLPXuat
     */
    public TrangChuThuThu_QLPXuat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        jPK_tieuDe = new javax.swing.JPanel();
        lbK_tieuDe = new javax.swing.JLabel();
        btnK_veTrangTruoc = new javax.swing.JButton();
        jPK_qlPM = new javax.swing.JPanel();
        jPK_themPM = new javax.swing.JPanel();
        maPhieuxuatLabel = new javax.swing.JLabel();
        maPhieuXuatField = new javax.swing.JTextField();
        ngayXuatLabel = new javax.swing.JLabel();
        ngayXuatField = new javax.swing.JTextField();
        jPK_themMaSach = new javax.swing.JPanel();
        txtK_maPM_2 = new javax.swing.JTextField();
        labelTensach = new javax.swing.JLabel();
        txtK_maSach = new javax.swing.JTextField();
        labelMasach = new javax.swing.JLabel();
        labelSoluong = new javax.swing.JLabel();
        txtK_maSach6 = new javax.swing.JTextField();
        labelGia = new javax.swing.JLabel();
        txtK_maSach7 = new javax.swing.JTextField();
        labelMaphieuxuat = new javax.swing.JLabel();
        txtK_maSach4 = new javax.swing.JTextField();
        LabelTongtien = new javax.swing.JLabel();
        txtK_maSach8 = new javax.swing.JTextField();
        txtK_maSach9 = new javax.swing.JTextField();
        labelGhichu = new javax.swing.JLabel();
        jPK_button = new javax.swing.JPanel();
        jPK_btnQLPM = new javax.swing.JPanel();
        btnK_themPX = new javax.swing.JButton();
        btnK_luuPX = new javax.swing.JButton();
        btnExportPX = new javax.swing.JButton();
        btnK_suaPX = new javax.swing.JButton();
        btnRefreshPX = new javax.swing.JButton();
        DelBtnXuat = new javax.swing.JButton();
        jPK_btnQLS = new javax.swing.JPanel();
        btnK_themMaSach = new javax.swing.JButton();
        btnK_lamMoiPX = new javax.swing.JButton();
        btnK_luuMaSach = new javax.swing.JButton();
        btnK_suaPX1 = new javax.swing.JButton();
        DelBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPK_tieuDe.setBackground(new java.awt.Color(255, 204, 204));

        lbK_tieuDe.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbK_tieuDe.setForeground(java.awt.Color.darkGray);
        lbK_tieuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill.png"))); // NOI18N
        lbK_tieuDe.setText("QUẢN LÝ PHIẾU XUẤT");

        btnK_veTrangTruoc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnK_veTrangTruoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_previous.png"))); // NOI18N
        btnK_veTrangTruoc.setText("Về trang trước");
        btnK_veTrangTruoc.setToolTipText("");
        btnK_veTrangTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_veTrangTruocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPK_tieuDeLayout = new javax.swing.GroupLayout(jPK_tieuDe);
        jPK_tieuDe.setLayout(jPK_tieuDeLayout);
        jPK_tieuDeLayout.setHorizontalGroup(
            jPK_tieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPK_tieuDeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnK_veTrangTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addGap(329, 329, 329)
                .addComponent(lbK_tieuDe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPK_tieuDeLayout.setVerticalGroup(
            jPK_tieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPK_tieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPK_tieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                    .addComponent(lbK_tieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnK_veTrangTruoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPK_qlPM.setBackground(new java.awt.Color(255, 255, 204));

        jPK_themPM.setBackground(new java.awt.Color(204, 204, 255));
        jPK_themPM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        maPhieuxuatLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        maPhieuxuatLabel.setForeground(new java.awt.Color(0, 0, 0));
        maPhieuxuatLabel.setText("Mã phiếu xuất:");

        maPhieuXuatField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        ngayXuatLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ngayXuatLabel.setForeground(new java.awt.Color(0, 0, 0));
        ngayXuatLabel.setText("Ngày xuất:");

        ngayXuatField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPK_themPMLayout = new javax.swing.GroupLayout(jPK_themPM);
        jPK_themPM.setLayout(jPK_themPMLayout);
        jPK_themPMLayout.setHorizontalGroup(
            jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPK_themPMLayout.createSequentialGroup()

                .addGap(53, 53, 53)
                .addGroup(jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ngayXuatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maPhieuxuatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ngayXuatField)
                    .addComponent(maPhieuXuatField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(232, 232, 232))
        );
        jPK_themPMLayout.setVerticalGroup(
            jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPK_themPMLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maPhieuxuatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maPhieuXuatField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngayXuatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngayXuatField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPK_themMaSach.setBackground(new java.awt.Color(204, 204, 255));
        jPK_themMaSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtK_maPM_2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtK_maPM_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtK_maPM_2ActionPerformed(evt);
            }
        });

        labelTensach.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelTensach.setForeground(new java.awt.Color(0, 0, 0));
        labelTensach.setText("Tên sách:");

        txtK_maSach.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        labelMasach.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelMasach.setForeground(new java.awt.Color(0, 0, 0));
        labelMasach.setText("Mã sách:");

        labelSoluong.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelSoluong.setForeground(new java.awt.Color(0, 0, 0));
        labelSoluong.setText("Số lượng:");

        txtK_maSach6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        labelGia.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelGia.setForeground(new java.awt.Color(0, 0, 0));
        labelGia.setText("Giá:");

        txtK_maSach7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        labelMaphieuxuat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelMaphieuxuat.setForeground(new java.awt.Color(0, 0, 0));
        labelMaphieuxuat.setText("Mã phiếu xuất:");

        txtK_maSach4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        LabelTongtien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LabelTongtien.setForeground(new java.awt.Color(0, 0, 0));
        LabelTongtien.setText("Tổng tiền:");

        txtK_maSach8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtK_maSach9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        labelGhichu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelGhichu.setForeground(new java.awt.Color(0, 0, 0));
        labelGhichu.setText("Ghi chú:");

        javax.swing.GroupLayout jPK_themMaSachLayout = new javax.swing.GroupLayout(jPK_themMaSach);
        jPK_themMaSach.setLayout(jPK_themMaSachLayout);
        jPK_themMaSachLayout.setHorizontalGroup(
            jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPK_themMaSachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                        .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                                .addComponent(labelMasach)
                                .addGap(18, 18, 18)
                                .addComponent(txtK_maSach))
                            .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                                .addComponent(labelGhichu)
                                .addGap(23, 23, 23)
                                .addComponent(txtK_maSach9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                                .addComponent(labelSoluong)
                                .addGap(64, 64, 64)
                                .addComponent(txtK_maSach6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPK_themMaSachLayout.createSequentialGroup()
                                .addComponent(labelMaphieuxuat)
                                .addGap(18, 18, 18)
                                .addComponent(txtK_maSach4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                        .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTensach)
                            .addComponent(LabelTongtien))
                        .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(txtK_maPM_2))
                            .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtK_maSach8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelGia)
                        .addGap(107, 107, 107)
                        .addComponent(txtK_maSach7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPK_themMaSachLayout.setVerticalGroup(
            jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMasach, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtK_maSach, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMaphieuxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtK_maSach4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTensach, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelSoluong)
                        .addComponent(txtK_maSach6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtK_maPM_2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtK_maSach8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGia)
                    .addComponent(txtK_maSach7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGhichu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtK_maSach9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPK_button.setBackground(new java.awt.Color(255, 255, 204));


        javax.swing.GroupLayout jPK_buttonLayout = new javax.swing.GroupLayout(jPK_button);
        jPK_button.setLayout(jPK_buttonLayout);
        jPK_buttonLayout.setHorizontalGroup(
            jPK_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPK_buttonLayout.setVerticalGroup(
            jPK_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );

        jPK_btnQLPM.setBackground(new java.awt.Color(204, 204, 255));
        jPK_btnQLPM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPK_btnQLPM.setPreferredSize(new java.awt.Dimension(520, 84));


        btnK_themPX.setBackground(new java.awt.Color(255, 204, 204));
        btnK_themPX.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_themPX.setForeground(new java.awt.Color(0, 0, 0));
        btnK_themPX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        btnK_themPX.setText("Thêm");
        btnK_themPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_themPXActionPerformed(evt);
            }
        });

        btnK_luuPX.setBackground(new java.awt.Color(255, 204, 204));
        btnK_luuPX.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_luuPX.setForeground(new java.awt.Color(0, 0, 0));
        btnK_luuPX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/luu.png"))); // NOI18N
        btnK_luuPX.setText("Lưu");
        btnK_luuPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_luuPXActionPerformed(evt);
            }
        });

        btnExportPX.setBackground(new java.awt.Color(255, 204, 204));
        btnExportPX.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnExportPX.setForeground(new java.awt.Color(0, 0, 0));
        btnExportPX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/R_pixian_ai.png"))); // NOI18N
        btnExportPX.setText("Xuất");
        btnExportPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportPXActionPerformed(evt);
            }
        });

        btnK_suaPX.setBackground(new java.awt.Color(255, 204, 204));
        btnK_suaPX.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_suaPX.setForeground(new java.awt.Color(0, 0, 0));
        btnK_suaPX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exchange1.png"))); // NOI18N
        btnK_suaPX.setText("Sửa");
        btnK_suaPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_suaPXActionPerformed(evt);
            }
        });

        btnRefreshPX.setBackground(new java.awt.Color(255, 204, 204));
        btnRefreshPX.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnRefreshPX.setForeground(new java.awt.Color(0, 0, 0));
        btnRefreshPX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eraser.png"))); // NOI18N
        btnRefreshPX.setText("Làm mới");
        btnRefreshPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshPXActionPerformed(evt);
            }
        });

        DelBtnXuat.setBackground(new java.awt.Color(255, 204, 204));
        DelBtnXuat.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        DelBtnXuat.setForeground(new java.awt.Color(0, 0, 0));
        DelBtnXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa.png"))); // NOI18N
        DelBtnXuat.setText("Xóa");
        DelBtnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelBtnXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPK_btnQLPMLayout = new javax.swing.GroupLayout(jPK_btnQLPM);
        jPK_btnQLPM.setLayout(jPK_btnQLPMLayout);
        jPK_btnQLPMLayout.setHorizontalGroup(
            jPK_btnQLPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPK_btnQLPMLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPK_btnQLPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPK_btnQLPMLayout.createSequentialGroup()
                        .addComponent(btnK_themPX, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnK_suaPX, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPK_btnQLPMLayout.createSequentialGroup()
                        .addComponent(btnK_luuPX, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExportPX, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPK_btnQLPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRefreshPX)
                    .addComponent(DelBtnXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPK_btnQLPMLayout.setVerticalGroup(
            jPK_btnQLPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPK_btnQLPMLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPK_btnQLPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnK_themPX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnK_suaPX)
                    .addComponent(DelBtnXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPK_btnQLPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnK_luuPX)
                    .addComponent(btnExportPX, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshPX))
                .addGap(21, 21, 21))
        );

        jPK_btnQLS.setBackground(new java.awt.Color(204, 204, 255));
        jPK_btnQLS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPK_btnQLS.setPreferredSize(new java.awt.Dimension(540, 84));

        btnK_themMaSach.setBackground(new java.awt.Color(255, 204, 204));
        btnK_themMaSach.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_themMaSach.setForeground(new java.awt.Color(0, 0, 0));
        btnK_themMaSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/them.png"))); // NOI18N
        btnK_themMaSach.setText("Thêm");
        btnK_themMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_themMaSachActionPerformed(evt);
            }
        });

        btnK_lamMoiPX.setBackground(new java.awt.Color(255, 204, 204));
        btnK_lamMoiPX.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_lamMoiPX.setForeground(new java.awt.Color(0, 0, 0));
        btnK_lamMoiPX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eraser.png"))); // NOI18N
        btnK_lamMoiPX.setText("Làm mới");
        btnK_lamMoiPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_lamMoiPXActionPerformed(evt);
            }
        });

        btnK_luuMaSach.setBackground(new java.awt.Color(255, 204, 204));
        btnK_luuMaSach.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_luuMaSach.setForeground(new java.awt.Color(0, 0, 0));
        btnK_luuMaSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/luu.png"))); // NOI18N
        btnK_luuMaSach.setText("Lưu");
        btnK_luuMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_luuMaSachActionPerformed(evt);
            }
        });

        btnK_suaPX1.setBackground(new java.awt.Color(255, 204, 204));
        btnK_suaPX1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_suaPX1.setForeground(new java.awt.Color(0, 0, 0));
        btnK_suaPX1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exchange1.png"))); // NOI18N
        btnK_suaPX1.setText("Sửa");
        btnK_suaPX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_suaPX1ActionPerformed(evt);
            }
        });

        DelBtn.setBackground(new java.awt.Color(255, 204, 204));
        DelBtn.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        DelBtn.setForeground(new java.awt.Color(0, 0, 0));
        DelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa.png"))); // NOI18N
        DelBtn.setText("Xóa");
        DelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPK_btnQLSLayout = new javax.swing.GroupLayout(jPK_btnQLS);
        jPK_btnQLS.setLayout(jPK_btnQLSLayout);
        jPK_btnQLSLayout.setHorizontalGroup(
            jPK_btnQLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPK_btnQLSLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPK_btnQLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnK_themMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnK_luuMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPK_btnQLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPK_btnQLSLayout.createSequentialGroup()
                        .addComponent(btnK_suaPX1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnK_lamMoiPX))
                .addGap(132, 132, 132))
        );
        jPK_btnQLSLayout.setVerticalGroup(
            jPK_btnQLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPK_btnQLSLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPK_btnQLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                    .addComponent(btnK_themMaSach)
                    .addComponent(btnK_suaPX1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPK_btnQLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnK_luuMaSach)
                    .addComponent(btnK_lamMoiPX))
                .addGap(22, 22, 22))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã phiếu xuất", "Ngày xuất", "Tổng tiền"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Mã phiếu xuất", "Số lượng", "Giá", "Tổng tiền", "Ghi chú"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPK_qlPMLayout = new javax.swing.GroupLayout(jPK_qlPM);
        jPK_qlPM.setLayout(jPK_qlPMLayout);
        jPK_qlPMLayout.setHorizontalGroup(
            jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPK_qlPMLayout.createSequentialGroup()

                .addComponent(jPK_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1293, 1293, 1293))
            .addGroup(jPK_qlPMLayout.createSequentialGroup()
                .addGroup(jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPK_btnQLPM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPK_qlPMLayout.createSequentialGroup()
                        .addComponent(jPK_themPM, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPK_qlPMLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addGap(18, 18, 18)
                .addGroup(jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPK_btnQLS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addComponent(jPK_themMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPK_qlPMLayout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())))
        );
        jPK_qlPMLayout.setVerticalGroup(
            jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPK_qlPMLayout.createSequentialGroup()
                .addContainerGap()

                .addGroup(jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPK_themPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPK_themMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPK_btnQLS, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jPK_btnQLPM, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(430, 430, 430)
                .addComponent(jPK_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPK_tieuDe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                    .addComponent(jPK_qlPM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPK_tieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                .addComponent(jPK_qlPM, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnK_veTrangTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_veTrangTruocActionPerformed

    }//GEN-LAST:event_btnK_veTrangTruocActionPerformed

    private void btnK_themPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_themPXActionPerformed

    }//GEN-LAST:event_btnK_themPXActionPerformed

    private void btnK_luuPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_luuPXActionPerformed

    }//GEN-LAST:event_btnK_luuPXActionPerformed

    private void btnExportPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportPXActionPerformed

    private void btnK_suaPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_suaPXActionPerformed

    }//GEN-LAST:event_btnK_suaPXActionPerformed

    private void btnRefreshPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshPXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshPXActionPerformed

    private void DelBtnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelBtnXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DelBtnXuatActionPerformed

    private void btnK_themMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_themMaSachActionPerformed

    }//GEN-LAST:event_btnK_themMaSachActionPerformed

    private void btnK_lamMoiPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_lamMoiPXActionPerformed

    }//GEN-LAST:event_btnK_lamMoiPXActionPerformed

    private void btnK_luuMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_luuMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnK_luuMaSachActionPerformed

    private void btnK_suaPX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK_suaPX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnK_suaPX1ActionPerformed

    private void DelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelBtnActionPerformed

    }//GEN-LAST:event_DelBtnActionPerformed

    private void txtK_maPM_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtK_maPM_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtK_maPM_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(TrangChuThuThu_QLPXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuThuThu_QLPXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuThuThu_QLPXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuThuThu_QLPXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new TrangChuThuThu_QLPXuat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JButton DelBtn;
    private javax.swing.JButton DelBtnXuat;
    private javax.swing.JLabel LabelTongtien;
    private javax.swing.JButton btnExportPX;
    private javax.swing.JButton btnK_lamMoiPX;
    private javax.swing.JButton btnK_luuMaSach;
    private javax.swing.JButton btnK_luuPX;
    private javax.swing.JButton btnK_suaPX;
    private javax.swing.JButton btnK_suaPX1;
    private javax.swing.JButton btnK_themMaSach;
    private javax.swing.JButton btnK_themPX;
    private javax.swing.JButton btnK_veTrangTruoc;
    private javax.swing.JButton btnRefreshPX;
    private javax.swing.JPanel jPK_btnQLPM;
    private javax.swing.JPanel jPK_btnQLS;
    private javax.swing.JPanel jPK_button;
    private javax.swing.JPanel jPK_qlPM;
    private javax.swing.JPanel jPK_themMaSach;
    private javax.swing.JPanel jPK_themPM;
    private javax.swing.JPanel jPK_tieuDe;

    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelGhichu;
    private javax.swing.JLabel labelGia;
    private javax.swing.JLabel labelMaphieuxuat;
    private javax.swing.JLabel labelMasach;
    private javax.swing.JLabel labelSoluong;
    private javax.swing.JLabel labelTensach;
    private javax.swing.JLabel lbK_tieuDe;
    private javax.swing.JTextField maPhieuXuatField;
    private javax.swing.JLabel maPhieuxuatLabel;
    private javax.swing.JTextField ngayXuatField;
    private javax.swing.JLabel ngayXuatLabel;
    private javax.swing.JTextField txtK_maPM_2;
    private javax.swing.JTextField txtK_maSach;
    private javax.swing.JTextField txtK_maSach4;
    private javax.swing.JTextField txtK_maSach6;
    private javax.swing.JTextField txtK_maSach7;
    private javax.swing.JTextField txtK_maSach8;
    private javax.swing.JTextField txtK_maSach9;
    // End of variables declaration//GEN-END:variables
}
