/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.*;
import DTO.ChiTietPhieuMuon;
import DTO.PhieuMuon;
import DTO.TacGia;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

/**
 *
 * @author nguye
 */
public class TrangChuThuThu_QLPM_1 extends javax.swing.JFrame {
    DefaultTableModel defaultTableModel_PM;
    DefaultTableModel defaultTableModel_CTPM;

    /**
     * Creates new form QuanLyPhieuMuon
     */
    public TrangChuThuThu_QLPM_1() {
        initComponents();
        loadmaPhieuMuon();
        loadComboBoxMaCanBo();
        loadComboBoxmaPhieuMuon();
    }

    public void loadmaPhieuMuon() {
        defaultTableModel_PM = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(defaultTableModel_PM);
        defaultTableModel_PM.addColumn("Mã phiếu mượn");
        defaultTableModel_PM.addColumn("Mã tài khoản");
        defaultTableModel_PM.addColumn("Số ngày mượn");
        defaultTableModel_PM.addColumn("Mã cán bộ");
        defaultTableModel_PM.addColumn("Ngày mượn");
        defaultTableModel_PM.addColumn("Ngày trả");
        defaultTableModel_PM.addColumn("Số lượng sách");
        defaultTableModel_PM.addColumn("Trạng thái");
        List<PhieuMuon> phieuMuonSach = PhieuMuon_DAO.getInstance().selectAll();
        for (PhieuMuon pms : phieuMuonSach) {
            defaultTableModel_PM.addRow(
                    new Object[] { pms.getMaPhieuMuon(), pms.getMaTaikhoan(), pms.getSoNgayMuon(), pms.getMaQuanly(),
                            pms.getNgayMuon(), pms.getHanTraSach(), pms.getSoLuongSach(), pms.getTrangThai() });
        }
    }

    public void loadChiTietPhieuMuon(String id) {
        defaultTableModel_CTPM = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable2.setModel(defaultTableModel_CTPM);
        defaultTableModel_CTPM.addColumn("Mã phiếu mượn");
        defaultTableModel_CTPM.addColumn("Mã sách");
        List<ChiTietPhieuMuon> chiTietPhieuNhapSaches = ChiTietPhieuMuon_DAO.getInstance().selectAllById(id);
        for (ChiTietPhieuMuon ctpns : chiTietPhieuNhapSaches) {
            defaultTableModel_CTPM.addRow(new Object[] { ctpns.getMaPhieumuon(), ctpns.getMaSach(), ctpns.getTinhTrangSach()});
        }
    }

    public void loadComboBoxMaCanBo() {
        List<String> QuanLys = PhieuMuon_DAO.getInstance().selectAllMaCanBo();
        for (String quanly : QuanLys) {
            cbbK_maCB.addItem(quanly);
        }
    }

    public void loadComboBoxmaPhieuMuon() {
        List<PhieuMuon> phieuNhapSaches = PhieuMuon_DAO.getInstance().selectAll();
        for (PhieuMuon pns : phieuNhapSaches) {
            cbbK_maPM.addItem(pns.getMaPhieuMuon());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPK_tieuDe = new javax.swing.JPanel();
        lbK_tieuDe = new javax.swing.JLabel();
        btnK_veTrangTruoc = new javax.swing.JButton();
        jPK_qlPM = new javax.swing.JPanel();
        jPK_themPM = new javax.swing.JPanel();
        lbK_maPM1 = new javax.swing.JLabel();
        txtK_maPM_1 = new javax.swing.JTextField();
        lbL_maTK = new javax.swing.JLabel();
        txtK_maTK = new javax.swing.JTextField();
        lbK_maCB = new javax.swing.JLabel();
        lbK_soNgayMuon = new javax.swing.JLabel();
        cbbK_soNgayMuon = new javax.swing.JComboBox<>();
        lbK_ngayMuon = new javax.swing.JLabel();
        txtK_ngayMuon = new com.toedter.calendar.JDateChooser();
        labelNgayTra = new javax.swing.JLabel();
        fieldNgayTra = new javax.swing.JTextField();
        lbK_trangThai = new javax.swing.JLabel();
        cbbK_trangThai = new javax.swing.JComboBox<>();
        cbbK_maCB = new javax.swing.JComboBox<>();
        labelSoluongsach = new javax.swing.JLabel();
        fieldSoluongsach = new javax.swing.JTextField();
        jPK_themMaSach = new javax.swing.JPanel();
        txtK_maSach = new javax.swing.JTextField();
        lbK_maSach = new javax.swing.JLabel();
        lbK_maPM3 = new javax.swing.JLabel();
        cbbK_maPM = new javax.swing.JComboBox<>();
        jPK_button = new javax.swing.JPanel();
        jPK_btnQLPM = new javax.swing.JPanel();
        btnK_themPM = new javax.swing.JButton();
        btnK_suaPM = new javax.swing.JButton();
        btnK_lamMoiPM = new javax.swing.JButton();
        btnK_luuPM = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnXuatPhieuMuon = new javax.swing.JButton();
        jPK_btnQLS = new javax.swing.JPanel();
        btnK_themMaSach = new javax.swing.JButton();
        btnK_lamMoiSach = new javax.swing.JButton();
        btnK_xoaMaSach = new javax.swing.JButton();
        btnK_luuMaSach = new javax.swing.JButton();
        btnK_suaPM1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));

        jPK_tieuDe.setBackground(new java.awt.Color(255, 204, 204));

        lbK_tieuDe.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbK_tieuDe.setForeground(java.awt.Color.darkGray);
        lbK_tieuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill.png"))); // NOI18N
        lbK_tieuDe.setText("QUẢN LÝ PHIẾU MƯỢN");

        btnK_veTrangTruoc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnK_veTrangTruoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_previous.png"))); // NOI18N
        btnK_veTrangTruoc.setText("Về trang trước");
        btnK_veTrangTruoc.setToolTipText("");
        btnK_veTrangTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_veTrangTruocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPK_tieuDeLayout = new javax.swing.GroupLayout(jPK_tieuDe);
        jPK_tieuDe.setLayout(jPK_tieuDeLayout);
        jPK_tieuDeLayout.setHorizontalGroup(
                jPK_tieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPK_tieuDeLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnK_veTrangTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 196,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(250, 250, 250)
                                .addComponent(lbK_tieuDe)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPK_tieuDeLayout.setVerticalGroup(
                jPK_tieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPK_tieuDeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        jPK_tieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lbK_tieuDe, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnK_veTrangTruoc, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));

        jPK_qlPM.setBackground(new java.awt.Color(255, 255, 204));

        jPK_themPM.setBackground(new java.awt.Color(204, 204, 255));
        jPK_themPM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbK_maPM1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbK_maPM1.setForeground(new java.awt.Color(0, 0, 0));
        lbK_maPM1.setText("Mã phiếu mượn:");

        txtK_maPM_1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lbL_maTK.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbL_maTK.setForeground(new java.awt.Color(0, 0, 0));
        lbL_maTK.setText("Mã tài khoản:");

        txtK_maTK.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lbK_maCB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbK_maCB.setForeground(new java.awt.Color(0, 0, 0));
        lbK_maCB.setText("Mã cán bộ:");

        lbK_soNgayMuon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbK_soNgayMuon.setForeground(new java.awt.Color(0, 0, 0));
        lbK_soNgayMuon.setText("Số ngày mượn:");

        cbbK_soNgayMuon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbbK_soNgayMuon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "14", "21" }));

        lbK_ngayMuon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbK_ngayMuon.setForeground(new java.awt.Color(0, 0, 0));
        lbK_ngayMuon.setText("Ngày mượn:");

        txtK_ngayMuon.setDateFormatString("yyyy-MM-dd");

        labelNgayTra.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelNgayTra.setForeground(new java.awt.Color(0, 0, 0));
        labelNgayTra.setText("Ngày trả:");

        fieldNgayTra.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lbK_trangThai.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbK_trangThai.setForeground(new java.awt.Color(0, 0, 0));
        lbK_trangThai.setText("Trạng thái:");

        cbbK_trangThai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbbK_trangThai.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa trả", "Đã trả", "Chưa duyệt", " " }));

        cbbK_maCB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        labelSoluongsach.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelSoluongsach.setForeground(new java.awt.Color(0, 0, 0));
        labelSoluongsach.setText("Số lượng sách:");

        fieldSoluongsach.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPK_themPMLayout = new javax.swing.GroupLayout(jPK_themPM);
        jPK_themPM.setLayout(jPK_themPMLayout);
        jPK_themPMLayout.setHorizontalGroup(
                jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPK_themPMLayout.createSequentialGroup()
                                .addContainerGap(72, Short.MAX_VALUE)
                                .addGroup(jPK_themPMLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPK_themPMLayout.createSequentialGroup()
                                                .addGroup(jPK_themPMLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addGroup(jPK_themPMLayout.createSequentialGroup()
                                                                .addGroup(jPK_themPMLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lbK_maPM1)
                                                                        .addComponent(lbK_soNgayMuon))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPK_themPMLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(txtK_maPM_1)
                                                                        .addComponent(cbbK_soNgayMuon,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                163,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(5, 5, 5))
                                                        .addGroup(jPK_themPMLayout.createSequentialGroup()
                                                                .addComponent(lbK_ngayMuon)
                                                                .addGap(39, 39, 39)
                                                                .addComponent(txtK_ngayMuon,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 170,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPK_themPMLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPK_themPMLayout.createSequentialGroup()
                                                                .addComponent(lbL_maTK,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 123,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtK_maTK,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 175,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPK_themPMLayout.createSequentialGroup()
                                                                .addGroup(jPK_themPMLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lbK_maCB,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                110,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(labelNgayTra))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPK_themPMLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(fieldNgayTra,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                170,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cbbK_maCB,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                175,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cbbK_trangThai,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                176,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(jPK_themPMLayout.createSequentialGroup()
                                                .addComponent(labelSoluongsach)
                                                .addGap(27, 27, 27)
                                                .addComponent(fieldSoluongsach, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lbK_trangThai, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(69, Short.MAX_VALUE)));
        jPK_themPMLayout.setVerticalGroup(
                jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPK_themPMLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(
                                        jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtK_maPM_1, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbK_maPM1, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtK_maTK, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbL_maTK))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPK_themPMLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                        .addComponent(lbK_soNgayMuon, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbbK_soNgayMuon)
                                        .addComponent(cbbK_maCB, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbK_maCB, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(13, 13, 13)
                                .addGroup(jPK_themPMLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPK_themPMLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lbK_ngayMuon, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtK_ngayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                                        Short.MAX_VALUE))
                                        .addGroup(jPK_themPMLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(labelNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fieldNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(
                                        jPK_themPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(labelSoluongsach, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(fieldSoluongsach, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbK_trangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbbK_trangThai, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(14, Short.MAX_VALUE)));

        jPK_themMaSach.setBackground(new java.awt.Color(204, 204, 255));
        jPK_themMaSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtK_maSach.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lbK_maSach.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbK_maSach.setForeground(new java.awt.Color(0, 0, 0));
        lbK_maSach.setText("Mã sách:");

        lbK_maPM3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbK_maPM3.setForeground(new java.awt.Color(0, 0, 0));
        lbK_maPM3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/open-book.png"))); // NOI18N
        lbK_maPM3.setText("Mã phiếu mượn:");

        cbbK_maPM.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbbK_maPM.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbK_maPMItemStateChanged(evt);
            }
        });
        cbbK_maPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbK_maPMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPK_themMaSachLayout = new javax.swing.GroupLayout(jPK_themMaSach);
        jPK_themMaSach.setLayout(jPK_themMaSachLayout);
        jPK_themMaSachLayout.setHorizontalGroup(
                jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPK_themMaSachLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbK_maPM3)
                                        .addComponent(lbK_maSach))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPK_themMaSachLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtK_maSach, javax.swing.GroupLayout.PREFERRED_SIZE, 165,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbbK_maPM, javax.swing.GroupLayout.PREFERRED_SIZE, 165,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(209, 209, 209)));
        jPK_themMaSachLayout.setVerticalGroup(
                jPK_themMaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPK_themMaSachLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPK_themMaSachLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbK_maPM3, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbbK_maPM, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPK_themMaSachLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtK_maSach, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbK_maSach, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPK_button.setBackground(new java.awt.Color(255, 255, 204));

        jPK_btnQLPM.setBackground(new java.awt.Color(204, 204, 255));
        jPK_btnQLPM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPK_btnQLPM.setPreferredSize(new java.awt.Dimension(520, 84));

        btnK_themPM.setBackground(new java.awt.Color(255, 204, 204));
        btnK_themPM.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_themPM.setForeground(new java.awt.Color(0, 0, 0));
        btnK_themPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        btnK_themPM.setText("Thêm");
        btnK_themPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_themPMActionPerformed(evt);
            }
        });

        btnK_suaPM.setBackground(new java.awt.Color(255, 204, 204));
        btnK_suaPM.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_suaPM.setForeground(new java.awt.Color(0, 0, 0));
        btnK_suaPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exchange1.png"))); // NOI18N
        btnK_suaPM.setText("Sửa");
        btnK_suaPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_suaPMActionPerformed(evt);
            }
        });

        btnK_lamMoiPM.setBackground(new java.awt.Color(255, 204, 204));
        btnK_lamMoiPM.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_lamMoiPM.setForeground(new java.awt.Color(0, 0, 0));
        btnK_lamMoiPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eraser.png"))); // NOI18N
        btnK_lamMoiPM.setText("Làm mới");
        btnK_lamMoiPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_lamMoiPMActionPerformed(evt);
            }
        });

        btnK_luuPM.setBackground(new java.awt.Color(255, 204, 204));
        btnK_luuPM.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_luuPM.setForeground(new java.awt.Color(0, 0, 0));
        btnK_luuPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/luu.png"))); // NOI18N
        btnK_luuPM.setText("Lưu");
        btnK_luuPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_luuPMActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 204, 204));
        btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(0, 0, 0));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnXuatPhieuMuon.setBackground(new java.awt.Color(255, 204, 204));
        btnXuatPhieuMuon.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnXuatPhieuMuon.setForeground(new java.awt.Color(0, 0, 0));
        btnXuatPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/R_pixian_ai.png"))); // NOI18N
        btnXuatPhieuMuon.setText("Xuất");
        btnXuatPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatPhieuMuonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPK_btnQLPMLayout = new javax.swing.GroupLayout(jPK_btnQLPM);
        jPK_btnQLPM.setLayout(jPK_btnQLPMLayout);
        jPK_btnQLPMLayout.setHorizontalGroup(
                jPK_btnQLPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPK_btnQLPMLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPK_btnQLPMLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPK_btnQLPMLayout.createSequentialGroup()
                                                .addComponent(btnK_lamMoiPM)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnK_luuPM, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPK_btnQLPMLayout.createSequentialGroup()
                                                .addComponent(btnK_themPM, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnK_suaPM, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPK_btnQLPMLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnXuatPhieuMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 110,
                                                Short.MAX_VALUE))
                                .addContainerGap(338, Short.MAX_VALUE)));
        jPK_btnQLPMLayout.setVerticalGroup(
                jPK_btnQLPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPK_btnQLPMLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPK_btnQLPMLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnK_themPM)
                                        .addComponent(btnK_suaPM, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPK_btnQLPMLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnK_luuPM)
                                        .addComponent(btnK_lamMoiPM)
                                        .addComponent(btnXuatPhieuMuon, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(88, 88, 88)));

        jPK_btnQLS.setBackground(new java.awt.Color(204, 204, 255));
        jPK_btnQLS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPK_btnQLS.setPreferredSize(new java.awt.Dimension(540, 84));

        btnK_themMaSach.setBackground(new java.awt.Color(255, 204, 204));
        btnK_themMaSach.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_themMaSach.setForeground(new java.awt.Color(0, 0, 0));
        btnK_themMaSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/them.png"))); // NOI18N
        btnK_themMaSach.setText("Thêm");
        btnK_themMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_themMaSachActionPerformed(evt);
            }
        });

        btnK_lamMoiSach.setBackground(new java.awt.Color(255, 204, 204));
        btnK_lamMoiSach.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_lamMoiSach.setForeground(new java.awt.Color(0, 0, 0));
        btnK_lamMoiSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eraser.png"))); // NOI18N
        btnK_lamMoiSach.setText("Làm mới");
        btnK_lamMoiSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_lamMoiSachActionPerformed(evt);
            }
        });

        btnK_xoaMaSach.setBackground(new java.awt.Color(255, 204, 204));
        btnK_xoaMaSach.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_xoaMaSach.setForeground(new java.awt.Color(0, 0, 0));
        btnK_xoaMaSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa.png"))); // NOI18N
        btnK_xoaMaSach.setText("Xóa");
        btnK_xoaMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_xoaMaSachActionPerformed(evt);
            }
        });

        btnK_luuMaSach.setBackground(new java.awt.Color(255, 204, 204));
        btnK_luuMaSach.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_luuMaSach.setForeground(new java.awt.Color(0, 0, 0));
        btnK_luuMaSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/luu.png"))); // NOI18N
        btnK_luuMaSach.setText("Lưu");
        btnK_luuMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_luuMaSachActionPerformed(evt);
            }
        });

        btnK_suaPM1.setBackground(new java.awt.Color(255, 204, 204));
        btnK_suaPM1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnK_suaPM1.setForeground(new java.awt.Color(0, 0, 0));
        btnK_suaPM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exchange1.png"))); // NOI18N
        btnK_suaPM1.setText("Sửa");
        btnK_suaPM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK_suaPM1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPK_btnQLSLayout = new javax.swing.GroupLayout(jPK_btnQLS);
        jPK_btnQLS.setLayout(jPK_btnQLSLayout);
        jPK_btnQLSLayout.setHorizontalGroup(
                jPK_btnQLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPK_btnQLSLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPK_btnQLSLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPK_btnQLSLayout.createSequentialGroup()
                                                .addComponent(btnK_suaPM1, javax.swing.GroupLayout.PREFERRED_SIZE, 115,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnK_themMaSach, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPK_btnQLSLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(btnK_luuMaSach)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnK_lamMoiSach)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnK_xoaMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(296, 296, 296)));
        jPK_btnQLSLayout.setVerticalGroup(
                jPK_btnQLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPK_btnQLSLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(
                                        jPK_btnQLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnK_xoaMaSach, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnK_themMaSach)
                                                .addComponent(btnK_suaPM1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        jPK_btnQLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnK_luuMaSach)
                                                .addComponent(btnK_lamMoiSach))
                                .addContainerGap()));

        javax.swing.GroupLayout jPK_buttonLayout = new javax.swing.GroupLayout(jPK_button);
        jPK_button.setLayout(jPK_buttonLayout);
        jPK_buttonLayout.setHorizontalGroup(
                jPK_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPK_buttonLayout.createSequentialGroup()
                                .addComponent(jPK_btnQLPM, javax.swing.GroupLayout.PREFERRED_SIZE, 780,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPK_btnQLS, javax.swing.GroupLayout.PREFERRED_SIZE, 500,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));
        jPK_buttonLayout.setVerticalGroup(
                jPK_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPK_btnQLS, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(jPK_btnQLPM, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE));

        javax.swing.GroupLayout jPK_qlPMLayout = new javax.swing.GroupLayout(jPK_qlPM);
        jPK_qlPM.setLayout(jPK_qlPMLayout);
        jPK_qlPMLayout.setHorizontalGroup(
                jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPK_qlPMLayout.createSequentialGroup()
                                .addGroup(jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPK_qlPMLayout.createSequentialGroup()
                                                .addComponent(jPK_themPM, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPK_themMaSach, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        500, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPK_button, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, 0)));
        jPK_qlPMLayout.setVerticalGroup(
                jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPK_qlPMLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPK_qlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPK_themPM, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPK_themMaSach, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPK_button, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null }
                },
                new String[] {
                        "Mã phiếu mượn", "Mã tài khoản", "Số ngày mượn", "Mã cán bộ", "Ngày mượn", "Ngày trả",
                        "Số lượng sách", "Trạng thái"
                }));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã phiếu mượn", "Mã sách", "Tình trạng sách"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPK_tieuDe, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPK_qlPM, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27,
                                                        Short.MAX_VALUE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPK_tieuDe, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPK_qlPM, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293,
                                                Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(MouseEvent evt) {// GEN-FIRST:event_QLTGiaTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        cbbK_maPM.setSelectedItem((String) jTable1.getValueAt(selectedRow, 0));
        txtK_maPM_1.setText((String) jTable1.getValueAt(selectedRow, 0));
        txtK_maTK.setText((String) jTable1.getValueAt(selectedRow, 1));
        cbbK_soNgayMuon.setSelectedItem(String.valueOf(jTable1.getValueAt(selectedRow, 2)));
        cbbK_maCB.setSelectedItem((String) jTable1.getValueAt(selectedRow, 3));
        Object selectedValue = jTable1.getValueAt(selectedRow, 4);
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = null;

        try {
            date = dateFormat.parse(String.valueOf(selectedValue));
        } catch (ParseException e) {
            e.printStackTrace();
        }
        txtK_ngayMuon.setDate(date);
        fieldNgayTra.setText(jTable1.getValueAt(selectedRow, 5).toString());
        fieldSoluongsach.setText(String.valueOf(jTable1.getValueAt(selectedRow, 6)));
        cbbK_trangThai.setSelectedItem((String) jTable1.getValueAt(selectedRow, 7));

        // txtK_maPM_1.setEnabled(true);
        // txtK_maTK.setEnabled(true);
        // fieldNgayTra.setEnabled(true);
        // fieldSoluongsach.setEnabled(true);
        // fieldNgayTra.setEnabled(true);
        // btnK_luuPM.setEnabled(true);
        // btnK_themPM.setEnabled(false);
        // btnXoa.setEnabled(false);
    }// GEN-LAST:event_QLTGiaTableMouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_QLTGiaTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable2.getSelectedRow();
        cbbK_maPM.setSelectedItem((String) jTable2.getValueAt(selectedRow, 0));
        txtK_maSach.setText((String) jTable2.getValueAt(selectedRow, 1));
        //fieldTinhtrangsach.setText((String) jTable2.getValueAt(selectedRow, 2));
//        txtK_maSach.setEnabled(true);
//        fieldTinhtrangsach.setEnabled(true);
//        btnK_luuPM.setEnabled(true);
//        btnK_themMaSach.setEnabled(false);
//        // btnK_suaPM1.setEnabled(false);
//        btnK_xoaMaSach.setEnabled(false);
    }

    private void btnK_themPMActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnK_themPMActionPerformed
        txtK_maPM_1.setEnabled(true);
        txtK_maTK.setEnabled(true);
        txtK_ngayMuon.setEnabled(true);
        fieldNgayTra.setEnabled(true);
        fieldSoluongsach.setEnabled(false);
        fieldSoluongsach.setText("0");
        btnK_luuPM.setEnabled(true);
        // btnK_themPM.setEnabled(false);
        btnK_suaPM.setEnabled(false);
        btnXoa.setEnabled(false);
    }// GEN-LAST:event_btnK_themPMActionPerformed

    private void btnK_luuPMActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnK_luuPMActionPerformed
        if (txtK_maPM_1.getText().equals("") && (btnK_suaPM.isEnabled() || btnXoa.isEnabled())) {
            JOptionPane.showMessageDialog(null, "Bạn chưa điền mã phiếu mượn.");
        } else {
            if (btnXoa.isEnabled()) {
                int result = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa?", "Xác nhận xóa",
                        JOptionPane.OK_CANCEL_OPTION);
                if (result == JOptionPane.OK_OPTION) {
                    if (PhieuMuon_DAO.getInstance().delete(txtK_maPM_1.getText()) > 0) {
                        JOptionPane.showMessageDialog(null, "Xóa phiếu mượn thành công!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Xóa phiếu mượn thất bại!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Hủy xóa.");
                }
            } else {
                PhieuMuon phieuMuon = new PhieuMuon();
                phieuMuon.setMaPhieuMuon(txtK_maPM_1.getText());
                phieuMuon.setSoNgayMuon(Integer.parseInt((String) cbbK_soNgayMuon.getSelectedItem()));
                Date date = txtK_ngayMuon.getDate();
                // Chuyển đổi từ Date sang LocalDate
                LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                phieuMuon.setNgayMuon(localDate);
                phieuMuon.setSoLuongSach(Integer.parseInt(fieldSoluongsach.getText()));
                phieuMuon.setMaTaikhoan(txtK_maTK.getText());
                phieuMuon.setMaQuanly((String) cbbK_maCB.getSelectedItem());
                phieuMuon.setTrangThai((String) cbbK_trangThai.getSelectedItem());
                if (btnK_themPM.isEnabled()) {
                    if (PhieuMuon_DAO.getInstance().add(phieuMuon) > 0) {
                        JOptionPane.showMessageDialog(null, "Thêm phiếu mượn thành công!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Thêm phiếu mượn thất bại!");
                    }
                } else if (btnK_suaPM.isEnabled()) {
                    if (PhieuMuon_DAO.getInstance().update(phieuMuon) > 0) {
                        JOptionPane.showMessageDialog(null, "Sửa phiếu mượn thành công!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Sửa phiếu mượn thất bại!");
                    }
                }
            }

            btnK_lamMoiPMActionPerformed(evt);
            loadmaPhieuMuon();
        }
    }// GEN-LAST:event_btnK_luuPMActionPerformed

    private void btnK_suaPMActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnK_suaPMActionPerformed
        txtK_maPM_1.setEnabled(true);
        txtK_maTK.setEnabled(true);
        txtK_ngayMuon.setEnabled(true);
        fieldNgayTra.setEnabled(true);
        fieldSoluongsach.setEnabled(true);
        btnK_luuPM.setEnabled(true);
        btnK_themPM.setEnabled(false);
        // btnK_suaPM.setEnabled(false);
        btnXoa.setEnabled(false);
    }// GEN-LAST:event_btnK_suaPMActionPerformed

    private void btnK_lamMoiPMActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnK_lamMoiPMActionPerformed
        txtK_maPM_1.setText("");
        txtK_maTK.setText("");
        txtK_ngayMuon.setDate(Date.from(Instant.now()));
        fieldNgayTra.setText("");
        fieldSoluongsach.setText("");

        txtK_maPM_1.setEnabled(true);
        txtK_maTK.setEnabled(true);
        txtK_ngayMuon.setEnabled(true);
        fieldNgayTra.setEnabled(true);
        fieldSoluongsach.setEnabled(true);
        btnK_themPM.setEnabled(true);
        btnK_suaPM.setEnabled(true);
        btnXoa.setEnabled(true);
    }// GEN-LAST:event_btnK_lamMoiPMActionPerformed

    private void btnK_themMaSachActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnK_themMaSachActionPerformed
        txtK_maSach.setEnabled(true);
        // fieldTinhtrangsach.setEnabled(true);
        btnK_luuMaSach.setEnabled(true);
        // btnK_themMaSach.setEnabled(false);
        btnK_suaPM1.setEnabled(false);
        btnK_xoaMaSach.setEnabled(false);
    }// GEN-LAST:event_btnK_themMaSachActionPerformed

    private void cbbK_maPMItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_cbbK_maPMItemStateChanged

    }// GEN-LAST:event_cbbK_maPMItemStateChanged

    private void btnK_luuMaSachActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnK_luuMaSachActionPerformed
        // TODO add your handling code here:
        if (txtK_maSach.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn chưa điền mã sách.");
        } else {
            ChiTietPhieuMuon chiTietPhieuMuon = new ChiTietPhieuMuon();
            chiTietPhieuMuon.setMaSach(txtK_maSach.getText());
            // chiTietPhieuMuon.setTinhTrangSach(fieldTinhtrangsach.getText());
            chiTietPhieuMuon.setMaPhieumuon((String) cbbK_maPM.getSelectedItem());
            if (btnK_themMaSach.isEnabled()) {
                if (ChiTietPhieuMuon_DAO.getInstance().add(chiTietPhieuMuon) > 0) {
                    JOptionPane.showMessageDialog(null, "Thêm phiếu chi tiết mượn thành công!");
                } else {
                    JOptionPane.showMessageDialog(null, "Thêm phiếu chi tiết mượn thất bại!");
                }
            } else if (btnK_suaPM1.isEnabled()) {

                if (ChiTietPhieuMuon_DAO.getInstance().update(chiTietPhieuMuon) > 0) {
                    JOptionPane.showMessageDialog(null, "Sửa phiếu chi tiết mượn thành công!");
                } else {
                    JOptionPane.showMessageDialog(null, "Sửa phiếu chi tiết mượn thất bại!");
                }
            } else if (btnK_xoaMaSach.isEnabled()) {
                int result = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa?", "Xác nhận xóa",
                        JOptionPane.OK_CANCEL_OPTION);
                if (result == JOptionPane.OK_OPTION) {
                    if (ChiTietPhieuMuon_DAO.getInstance().delete(chiTietPhieuMuon.getMaPhieumuon(),
                            chiTietPhieuMuon.getMaSach()) > 0) {
                        JOptionPane.showMessageDialog(null, "Xóa phiếu chi tiết mượn thành công!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Xóa phiếu chi tiết mượn thất bại!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Hủy xóa.");
                }
            }
            btnK_lamMoiSachActionPerformed(evt);
            loadChiTietPhieuMuon((String) cbbK_maPM.getSelectedItem());
            loadmaPhieuMuon();
        }

    }// GEN-LAST:event_btnK_luuMaSachActionPerformed

    private void btnK_lamMoiSachActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnK_lamMoiSachActionPerformed
        txtK_maSach.setText("");
        // fieldTinhtrangsach.setText("");
        txtK_maSach.setEnabled(true);
        // fieldTinhtrangsach.setEnabled(true);
        btnK_luuMaSach.setEnabled(false);
        btnK_themMaSach.setEnabled(true);

        btnK_xoaMaSach.setEnabled(true);
    }// GEN-LAST:event_btnK_lamMoiSachActionPerformed

    private void btnK_veTrangTruocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnK_veTrangTruocActionPerformed
        new TrangChuThuThu().setVisible(true);
        this.setVisible(false);
    }// GEN-LAST:event_btnK_veTrangTruocActionPerformed

    private void cbbK_maPMActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbbK_maPMActionPerformed
        // TODO add your handling code here:
        PhieuMuon phieuMuon = PhieuMuon_DAO.getInstance().selectById(cbbK_maPM.getSelectedItem().toString());
        txtK_maPM_1.setText(phieuMuon.getMaPhieuMuon());
        txtK_maTK.setText(phieuMuon.getMaTaikhoan());
        cbbK_soNgayMuon.setSelectedItem(String.valueOf(phieuMuon.getSoNgayMuon()));
        cbbK_maCB.setSelectedItem(phieuMuon.getMaQuanly());
        Object selectedValue = phieuMuon.getNgayMuon().toString();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = null;

        try {
            date = dateFormat.parse(String.valueOf(selectedValue));
        } catch (ParseException e) {
            e.printStackTrace();
        }
        txtK_ngayMuon.setDate(date);
        fieldNgayTra.setText(phieuMuon.getHanTraSach().toString());
        fieldSoluongsach.setText(String.valueOf(phieuMuon.getSoLuongSach()));
        cbbK_trangThai.setSelectedItem(phieuMuon.getTrangThai());
        loadChiTietPhieuMuon(phieuMuon.getMaPhieuMuon());

    }// GEN-LAST:event_cbbK_maPMActionPerformed

    private void cbbK_soNgayMuonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Date currentDate = txtK_ngayMuon.getDate();
        if (currentDate == null) {
            currentDate = new Date();
        }
        int numberOfDaysToAdd = Integer.parseInt((String) cbbK_soNgayMuon.getSelectedItem());
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(currentDate);
        calendar.add(Calendar.DAY_OF_MONTH, numberOfDaysToAdd);
        Date newDate = calendar.getTime();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dateString = dateFormat.format(newDate);
        fieldNgayTra.setText(dateString);
    }

    private void btnK_xoaMaSachActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnK_xoaMaSachActionPerformed
        txtK_maSach.setEnabled(true);
        // fieldTinhtrangsach.setEnabled(true);
        btnK_luuMaSach.setEnabled(true);
        btnK_themMaSach.setEnabled(false);
        txtK_maSach.setText("");
        // fieldTinhtrangsach.setText("");
        // fieldTinhtrangsach.setEnabled(false);
        btnK_xoaMaSach.setEnabled(false);
    }// GEN-LAST:event_btnK_xoaMaSachActionPerformed

    private void btnK_suaPM1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnK_suaPM1ActionPerformed
        // TODO add your handling code here:
        txtK_maSach.setEnabled(true);
        // fieldTinhtrangsach.setEnabled(true);
        btnK_luuMaSach.setEnabled(true);
        btnK_themMaSach.setEnabled(false);
        // btnK_suaPM1.setEnabled(false);
        btnK_xoaMaSach.setEnabled(false);
    }// GEN-LAST:event_btnK_suaPM1ActionPerformed

    private void btnXuatPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXuatPhieuMuonActionPerformed
        // TODO add your handling code here:
        if (txtK_maPM_1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn chưa điền mã phiếu mượn.");
        } else {
            String url = JOptionPane.showInputDialog("Nhập đường dẫn lưu file: ");
            if (url.equals("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập đường dẫn lưu file.");
            } else {
                if (PhieuMuon_DAO.getInstance().XuatExcelPhieuMuon(txtK_maPM_1.getText(), url) > 0) {
                    JOptionPane.showMessageDialog(null, "Đã xuất file!");
                } else {
                    JOptionPane.showMessageDialog(null, "Xuất file thất bại! \n Vui lòng kiểm tra đường dẫn.");
                }
            }
        }
    }// GEN-LAST:event_btnXuatPhieuMuonActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        txtK_maPM_1.setEnabled(true);
        txtK_maTK.setEnabled(false);
        txtK_ngayMuon.setEnabled(false);
        fieldNgayTra.setEnabled(false);
        fieldSoluongsach.setEnabled(false);
        btnK_luuPM.setEnabled(true);
        btnK_themPM.setEnabled(false);
        btnK_suaPM.setEnabled(false);
        // btnXoa.setEnabled(false);
    }// GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuThuThu_QLPM_1.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuThuThu_QLPM_1.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuThuThu_QLPM_1.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuThuThu_QLPM_1.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuThuThu_QLPM_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnK_lamMoiPM;
    private javax.swing.JButton btnK_lamMoiSach;
    private javax.swing.JButton btnK_luuMaSach;
    private javax.swing.JButton btnK_luuPM;
    private javax.swing.JButton btnK_suaPM;
    private javax.swing.JButton btnK_suaPM1;
    private javax.swing.JButton btnK_themMaSach;
    private javax.swing.JButton btnK_themPM;
    private javax.swing.JButton btnK_veTrangTruoc;
    private javax.swing.JButton btnK_xoaMaSach;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatPhieuMuon;
    private javax.swing.JComboBox<String> cbbK_maCB;
    private javax.swing.JComboBox<String> cbbK_maPM;
    private javax.swing.JComboBox<String> cbbK_soNgayMuon;
    private javax.swing.JComboBox<String> cbbK_trangThai;
    private javax.swing.JTextField fieldNgayTra;
    private javax.swing.JTextField fieldSoluongsach;
    private javax.swing.JPanel jPK_btnQLPM;
    private javax.swing.JPanel jPK_btnQLS;
    private javax.swing.JPanel jPK_button;
    private javax.swing.JPanel jPK_qlPM;
    private javax.swing.JPanel jPK_themMaSach;
    private javax.swing.JPanel jPK_themPM;
    private javax.swing.JPanel jPK_tieuDe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelNgayTra;
    private javax.swing.JLabel labelSoluongsach;
    private javax.swing.JLabel lbK_maCB;
    private javax.swing.JLabel lbK_maPM1;
    private javax.swing.JLabel lbK_maPM3;
    private javax.swing.JLabel lbK_maSach;
    private javax.swing.JLabel lbK_ngayMuon;
    private javax.swing.JLabel lbK_soNgayMuon;
    private javax.swing.JLabel lbK_tieuDe;
    private javax.swing.JLabel lbK_trangThai;
    private javax.swing.JLabel lbL_maTK;
    private javax.swing.JTextField txtK_maPM_1;
    private javax.swing.JTextField txtK_maSach;
    private javax.swing.JTextField txtK_maTK;
    private com.toedter.calendar.JDateChooser txtK_ngayMuon;
    // End of variables declaration//GEN-END:variables
}
